config/routes.rb
Miletus::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'page#view', :name => 'index'

  post '/recheck-sru-records' => 'record#recheck_sru'

  get '/atom' => 'record#atom', :as => :current_atom
  get '/atom/:date' => 'record#atom', :as => :atom

  match '/records.atom' => redirect('/atom')
  get '/records.gexf' => 'record#gexf'
  get '/records.sitemap' => 'record#sitemap'

  get '/graph' => 'record#graph', :as => :concept_graph

  get '/records/:id.gexf' => 'record#gexf',
    :constraints => {:id => /\d+/}, :as => :concept_gexf

  get '/records/:uuid.:format' => 'record#view_format',
    :constraints => {
      :uuid => /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/,
      :format => /[a-z0-9\.]+/
    }, :as => :concept_format
  get '/records/:uuid' => 'record#view',
    :constraints => {
      :uuid => /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/
    }, :as => :concept
  get '/records/:id' => 'record#view',
    :constraints => {:id => /\d+/}, :as => :concept_id

  post '/records/:id/recheck-sru' => 'record#recheck_sru',
    :constraints => {:id => /\d+/}


  match '/oai' => 'oai#index'

  match '/browse' => 'record#index'

  match '/about' => 'page#view', :name => 'about'
  match '/contact' => 'page#view', :name => 'contact'

  match '/robots.txt' => 'seo#robots'
  match '/siteindex.xml' => 'seo#siteindex', :as => :siteindex
  match '/main.sitemap' => 'seo#sitemap'
  match '/pages.sitemap' => 'page#sitemap'
  match '/credits' => 'page#credits'
end

app/views/page/credits.html.haml
.page-header
  %h1 Credits

%p.lead
  This website contains images and content generously donated by others for
  public use.

%p
  = link_to 'Font Awesome', 'http://fortawesome.github.com/Font-Awesome'
  designed by Dave Gandy and others.
  %small.muted
    CC-BY

%p
  = link_to 'Gantt Chart',
    'http://thenounproject.com/noun/gantt-chart/#icon-No3702'
  designed by
  = link_to 'Jeremy Boatman', 'http://thenounproject.com/jeremyboatman'
  from The Noun Project.
  %small.muted
    CC-BY

%p
  = link_to 'Data',
    'http://thenounproject.com/noun/data/#icon-No4299'
  and
  = link_to 'Information Technology',
    'http://thenounproject.com/noun/information-technology/#icon-No4197'
  designed by
  = link_to 'United Nations OCHA', 'http://thenounproject.com/ochaavmu'
  from The Noun Project.
  %small.muted
    Public Domain

%p
  = link_to 'People',
    'http://thenounproject.com/noun/people/#icon-No2300'
  designed by
  = link_to 'Roman J. Sokolov', 'http://thenounproject.com/rjsokolov'
  from The Noun Project.
  %small.muted
    CC-BY

%p
  = link_to 'Fax Machine',
    'http://thenounproject.com/noun/fax-machine/#icon-No3569'
  designed by
  = link_to 'Braden Stranks', 'http://thenounproject.com/bradenstranks'
  from The Noun Project.
  %small.muted
    CC-BY

app/views/page/not_found.html.haml
.row-fluid
  .span12
    %div{:style => 'height: 150px'}

.row-fluid
  .span12
    %p.muted{:style => 'text-align: center'}
      This page doesn't exist yet.
      Perhaps an administrator should
      = link_to "create the page", new_admin_page_path('page[name]' => @name)
      first.

.row-fluid
  .span12
    %div{:style => 'height: 150px'}

app/views/page/view.html.haml
.row-fluid
  .span12= @html